### ISSUE TITLE
Färdigkorrat 409

### ISSUE THREAD

**Issue by borstell** [robertostling/ud-swl#3]
Nu har jag gått igenom filen "*409.eaf" och korrat det som jag tycker behövts korras (mest smådetaljer). Jag kan nog inte bistå med så mycket mer nu, utan föreslår att Robert genererar html-träd från denna och sen kan de som vill kontrollera träden och se om det ser rätt ut.

**Comment by robertostling** [comment]
Tack! Här är HTML-versionen:
[swl-ud-train.zip](https://github.com/robertostling/ud-swl/files/537096/swl-ud-train.zip)
